const categoriesData = [
  { name: 'Hotels', slug: 'hotels', key: 'hotels', icon: 'hotel', color: '#E8D5B7', order: 1, isFeatured: true },
  { name: 'Things To Do', slug: 'things-to-do', key: 'thingsToDo', icon: 'activity', color: '#B7D9E8', order: 2, isFeatured: true },
  { name: 'Restaurants', slug: 'restaurants', key: 'restaurants', icon: 'restaurant', color: '#FFD5B7', order: 3, isFeatured: true },
  { name: 'Shops', slug: 'shops', key: 'shops', icon: 'shopping-bag', color: '#D5FFB7', order: 4, isFeatured: true },
  { name: 'World Tribes', slug: 'world-tribes', key: 'tribes', icon: 'globe', color: '#E8B7D5', order: 5, isFeatured: true },
  { name: 'Kids World', slug: 'kids-world', key: 'kidsWorld', icon: 'smile', color: '#FFEEB7', order: 6, isFeatured: true },
  { name: 'Destinations', slug: 'destinations', key: 'destinations', icon: 'map-pin', color: '#C5E8B7', order: 7, isFeatured: true },
];

const subtypesData = [
  { name: 'Heritage Hotel', slug: 'heritage-hotel', key: 'heritage_hotel', categoryKey: 'hotels', order: 1 },
  { name: 'Resort', slug: 'resort', key: 'resort', categoryKey: 'hotels', order: 2 },
  { name: 'Boutique Stay', slug: 'boutique-stay', key: 'boutique_stay', categoryKey: 'hotels', order: 3 },
  { name: 'Homestay', slug: 'homestay', key: 'homestay', categoryKey: 'hotels', order: 4 },
  { name: 'Lake View Stay', slug: 'lake-view-stay', key: 'lake_view_stay', categoryKey: 'hotels', order: 5 },
  { name: 'Same Day Tour', slug: 'same-day-tour', key: 'same_day_tour', categoryKey: 'thingsToDo', order: 1 },
  { name: 'Customized Tour', slug: 'customized-tour', key: 'customized_tour', categoryKey: 'thingsToDo', order: 2 },
  { name: 'Fixed Departure', slug: 'fixed-departure', key: 'fixed_departure', categoryKey: 'thingsToDo', order: 3 },
  { name: 'Adventure Activity', slug: 'adventure-activity', key: 'adventure_activity', categoryKey: 'thingsToDo', order: 4 },
  { name: 'Heritage Walk', slug: 'heritage-walk', key: 'heritage_walk', categoryKey: 'thingsToDo', order: 5 },
  { name: 'Food Trail', slug: 'food-trail', key: 'food_trail', categoryKey: 'thingsToDo', order: 6 },
  { name: 'Fine Dining', slug: 'fine-dining', key: 'fine_dining', categoryKey: 'restaurants', order: 1 },
  { name: 'Cafe', slug: 'cafe', key: 'cafe', categoryKey: 'restaurants', order: 2 },
  { name: 'Street Food', slug: 'street-food', key: 'street_food', categoryKey: 'restaurants', order: 3 },
  { name: 'Multi Cuisine', slug: 'multi-cuisine', key: 'multi_cuisine', categoryKey: 'restaurants', order: 4 },
  { name: 'Heritage Dining', slug: 'heritage-dining', key: 'heritage_dining', categoryKey: 'restaurants', order: 5 },
  { name: 'Rooftop Dining', slug: 'rooftop-dining', key: 'rooftop_dining', categoryKey: 'restaurants', order: 6 },
  { name: 'Handicraft Store', slug: 'handicraft-store', key: 'handicraft_store', categoryKey: 'shops', order: 1 },
  { name: 'Artisan Studio', slug: 'artisan-studio', key: 'artisan_studio', categoryKey: 'shops', order: 2 },
  { name: 'NGO Store', slug: 'ngo-store', key: 'ngo_store', categoryKey: 'shops', order: 3 },
  { name: 'Souvenir Shop', slug: 'souvenir-shop', key: 'souvenir_shop', categoryKey: 'shops', order: 4 },
  { name: 'Market Stall', slug: 'market-stall', key: 'market_stall', categoryKey: 'shops', order: 5 },
  { name: 'Handloom Bazaar', slug: 'handloom-bazaar', key: 'handloom_bazaar', categoryKey: 'shops', order: 6 },
  { name: 'Jewellery Market', slug: 'jewellery-market', key: 'jewellery_market', categoryKey: 'shops', order: 7 },
  { name: 'Cultural Experience', slug: 'cultural-experience', key: 'cultural_experience', categoryKey: 'tribes', order: 1 },
  { name: 'Tribal Workshop', slug: 'tribal-workshop', key: 'tribal_workshop', categoryKey: 'tribes', order: 2 },
  { name: 'Local Stay', slug: 'local-stay', key: 'local_stay', categoryKey: 'tribes', order: 3 },
  { name: 'Festival Event', slug: 'festival-event', key: 'festival_event', categoryKey: 'tribes', order: 4 },
  { name: 'Kids Camp', slug: 'kids-camp', key: 'kids_camp', categoryKey: 'kidsWorld', order: 1 },
  { name: 'Educational Workshop', slug: 'educational-workshop', key: 'educational_workshop', categoryKey: 'kidsWorld', order: 2 },
  { name: 'Sports Activity', slug: 'sports-activity', key: 'sports_activity', categoryKey: 'kidsWorld', order: 3 },
  { name: 'Arts & Crafts', slug: 'arts-crafts', key: 'arts_crafts', categoryKey: 'kidsWorld', order: 4 },
  { name: 'Honeymoon Package', slug: 'honeymoon-package', key: 'honeymoon_package', categoryKey: 'destinations', order: 1 },
  { name: 'Family Tour', slug: 'family-tour', key: 'family_tour', categoryKey: 'destinations', order: 2 },
  { name: 'Luxury Package', slug: 'luxury-package', key: 'luxury_package', categoryKey: 'destinations', order: 3 },
  { name: 'Budget Package', slug: 'budget-package', key: 'budget_package', categoryKey: 'destinations', order: 4 },
];

const citiesData = [
  { name: 'Jaipur', slug: 'jaipur', state: 'Rajasthan', isMetroCity: false, isFeatured: true, order: 1, geoLocation: { coordinates: [75.7873, 26.9124] }, popularFor: ['Heritage', 'Palaces', 'Shopping'], bestTimeToVisit: 'October to March' },
  { name: 'Delhi', slug: 'delhi', state: 'Delhi', isMetroCity: true, isFeatured: true, order: 2, geoLocation: { coordinates: [77.1025, 28.7041] }, popularFor: ['History', 'Food', 'Culture'] },
  { name: 'Mumbai', slug: 'mumbai', state: 'Maharashtra', isMetroCity: true, isFeatured: true, order: 3, geoLocation: { coordinates: [72.8777, 19.076] }, popularFor: ['Bollywood', 'Beaches', 'Nightlife'] },
  { name: 'Bangalore', slug: 'bangalore', state: 'Karnataka', isMetroCity: true, isFeatured: true, order: 4, geoLocation: { coordinates: [77.5946, 12.9716] }, popularFor: ['Tech', 'Gardens', 'Nightlife'] },
  { name: 'Goa', slug: 'goa', state: 'Goa', isMetroCity: false, isFeatured: true, order: 5, geoLocation: { coordinates: [74.124, 15.2993] }, popularFor: ['Beaches', 'Nightlife', 'Water Sports'], bestTimeToVisit: 'November to February' },
  { name: 'Udaipur', slug: 'udaipur', state: 'Rajasthan', isMetroCity: false, isFeatured: true, order: 6, geoLocation: { coordinates: [73.6833, 24.5854] }, popularFor: ['Lakes', 'Palaces', 'Romance'] },
  { name: 'Agra', slug: 'agra', state: 'Uttar Pradesh', isMetroCity: false, isFeatured: true, order: 7, geoLocation: { coordinates: [78.008, 27.1767] }, popularFor: ['Taj Mahal', 'Mughal Heritage'] },
  { name: 'Kerala', slug: 'kerala', state: 'Kerala', isMetroCity: false, isFeatured: true, order: 8, geoLocation: { coordinates: [76.2711, 10.8505] }, popularFor: ['Backwaters', 'Ayurveda', 'Nature'] },
  { name: 'Varanasi', slug: 'varanasi', state: 'Uttar Pradesh', isMetroCity: false, isFeatured: true, order: 9, geoLocation: { coordinates: [83.0043, 25.3176] }, popularFor: ['Ghats', 'Spirituality', 'Culture'] },
  { name: 'Shimla', slug: 'shimla', state: 'Himachal Pradesh', isMetroCity: false, isFeatured: true, order: 10, geoLocation: { coordinates: [77.1734, 31.1048] }, popularFor: ['Hill Station', 'Snow', 'Honeymoon'] },
  { name: 'Darjeeling', slug: 'darjeeling', state: 'West Bengal', isMetroCity: false, isFeatured: false, order: 11, geoLocation: { coordinates: [88.2663, 27.036] }, popularFor: ['Tea Gardens', 'Mountains', 'Toy Train'] },
  { name: 'Rishikesh', slug: 'rishikesh', state: 'Uttarakhand', isMetroCity: false, isFeatured: true, order: 12, geoLocation: { coordinates: [78.2676, 30.0869] }, popularFor: ['Yoga', 'River Rafting', 'Spirituality'] },
  { name: 'Kolkata', slug: 'kolkata', state: 'West Bengal', isMetroCity: true, isFeatured: false, order: 13, geoLocation: { coordinates: [88.3639, 22.5726] }, popularFor: ['Culture', 'Food', 'Durga Puja'] },
  { name: 'Chennai', slug: 'chennai', state: 'Tamil Nadu', isMetroCity: true, isFeatured: false, order: 14, geoLocation: { coordinates: [80.2707, 13.0827] }, popularFor: ['Temples', 'Beaches', 'Culture'] },
  { name: 'Hyderabad', slug: 'hyderabad', state: 'Telangana', isMetroCity: true, isFeatured: false, order: 15, geoLocation: { coordinates: [78.4867, 17.385] }, popularFor: ['Biryani', 'Heritage', 'Tech'] },
];

const seededAreas = [
  { citySlug: 'jaipur', name: 'Old City Loop', slug: 'old-city-loop', zoneType: 'tourist_zone', nearbyLandmarks: ['hawa mahal', 'city palace', 'jantar mantar'], popularRoutes: ['hawa mahal to city palace heritage walk', 'johari bazaar to tripolia bazaar trail'], clusterKey: 'pink-city-core', geoLocation: { coordinates: [75.8131, 26.9239] }, order: 1 },
  { citySlug: 'jaipur', name: 'Bapu Bazaar', slug: 'bapu-bazaar', zoneType: 'market_zone', nearbyLandmarks: ['clock tower', 'johari bazaar', 'tripolia bazaar'], popularRoutes: ['bapu bazaar shopping lane', 'clock tower snack crawl'], clusterKey: 'pink-city-market', geoLocation: { coordinates: [75.8244, 26.9131] }, order: 2 },
  { citySlug: 'jaipur', name: 'Amer Road', slug: 'amer-road', zoneType: 'mixed', nearbyLandmarks: ['amber fort', 'jal mahal'], popularRoutes: ['amber fort sunrise route', 'jal mahal lake stop'], clusterKey: 'pink-city-north', geoLocation: { coordinates: [75.8421, 26.9855] }, order: 3 },
  { citySlug: 'udaipur', name: 'Lake Pichola', slug: 'lake-pichola', zoneType: 'tourist_zone', nearbyLandmarks: ['city palace', 'jagdish temple', 'gangaur ghat'], popularRoutes: ['lake palace boat view route', 'ghat to palace sunset loop'], clusterKey: 'lake-city-core', geoLocation: { coordinates: [73.6858, 24.578] }, order: 1 },
  { citySlug: 'udaipur', name: 'Sadar Bazaar', slug: 'sadar-bazaar-udaipur', zoneType: 'market_zone', nearbyLandmarks: ['clock tower', 'bada bazaar', 'city palace'], popularRoutes: ['sadar bazaar shopping stretch', 'clock tower craft lane'], clusterKey: 'lake-city-market', geoLocation: { coordinates: [73.7029, 24.582] }, order: 2 },
  { citySlug: 'delhi', name: 'Chandni Chowk', slug: 'chandni-chowk', zoneType: 'market_zone', nearbyLandmarks: ['red fort', 'jama masjid', 'sis ganj gurudwara'], popularRoutes: ['paranthe wali gali crawl', 'red fort to spice market route'], clusterKey: 'old-delhi-core', geoLocation: { coordinates: [77.2311, 28.6562] }, order: 1 },
  { citySlug: 'delhi', name: 'Connaught Place', slug: 'connaught-place', zoneType: 'mixed', nearbyLandmarks: ['rajiv chowk', 'janpath', 'palika bazaar'], popularRoutes: ['inner circle cafe crawl', 'janpath craft walk'], clusterKey: 'ncr-central', geoLocation: { coordinates: [77.2167, 28.6315] }, order: 2 },
  { citySlug: 'varanasi', name: 'Dashashwamedh Ghat', slug: 'dashashwamedh-ghat', zoneType: 'tourist_zone', nearbyLandmarks: ['ganga aarti', 'kashi vishwanath temple', 'manikarnika ghat'], popularRoutes: ['evening aarti viewing loop', 'ghat to temple walk'], clusterKey: 'ghat-corridor', geoLocation: { coordinates: [83.0068, 25.3074] }, order: 1 },
  { citySlug: 'varanasi', name: 'Godowlia', slug: 'godowlia', zoneType: 'market_zone', nearbyLandmarks: ['vishwanath gali', 'maldahiya', 'dashashwamedh ghat'], popularRoutes: ['silk market shopping lane', 'gali snack trail'], clusterKey: 'ghat-market', geoLocation: { coordinates: [83.0052, 25.3079] }, order: 2 },
  { citySlug: 'goa', name: 'Baga Beach', slug: 'baga-beach', zoneType: 'tourist_zone', nearbyLandmarks: ['calangute beach', 'anjuna market', 'titos lane'], popularRoutes: ['beach sunset strip', 'night cafe crawl'], clusterKey: 'north-goa-beach', geoLocation: { coordinates: [73.7489, 15.5554] }, order: 1 },
  { citySlug: 'goa', name: 'Fontainhas', slug: 'panaji-fountainhas', zoneType: 'mixed', nearbyLandmarks: ['panjim church', 'old latin quarter', 'mandovi river'], popularRoutes: ['latin quarter walking route', 'riverfront evening promenade'], clusterKey: 'panaji-core', geoLocation: { coordinates: [73.8316, 15.4987] }, order: 2 },
];

const seededDiscoveryListings = [
  {
    slug: 'royal-kachori-lassi-house-jaipur',
    title: 'Royal Kachori & Lassi House',
    categoryKey: 'restaurants',
    subtypeKey: 'street_food',
    citySlug: 'jaipur',
    areaSlug: 'bapu-bazaar',
    vendorType: 'street_food',
    discoveryType: 'popular_choice',
    vendor: { businessName: 'Royal Kachori & Lassi House', slug: 'royal-kachori-lassi-house', description: 'Old city street food stop for kachori, lassi, and quick local plates.', shortDescription: 'Jaipur street food favourite near Bapu Bazaar.', ownerName: 'Aman Jain', ownerEmail: 'aman.jain@togetherinindia.example', ownerPassword: 'Vendor@12345', citySlug: 'jaipur', state: 'Rajasthan', tags: ['street food', 'kachori', 'lassi'], languages: ['Hindi', 'English'], yearEstablished: 2012 },
    location: { street: 'Bapu Bazaar Main Lane', area: 'Bapu Bazaar', city: 'Jaipur', state: 'Rajasthan', pincode: '302003', coordinates: [75.825, 26.9137] },
    tags: ['street food', 'lassi', 'local favourite', 'snacks'],
    nearbyLandmarks: ['clock tower', 'hawa mahal'],
    areaCluster: 'pink-city-market',
    labels: { popularChoice: true, superSaver: true, sponsored: false, featured: true, openNow: true },
    pricing: { priceType: 'range', currency: 'INR', basePrice: 120, discountedPrice: 99, minPrice: 80, maxPrice: 250, showPriceAs: 'range' },
    seoConfig: { metaTitle: 'Royal Kachori & Lassi House Jaipur', metaDescription: 'Discover Jaipur street food near Bapu Bazaar.', keywords: ['Jaipur food', 'kachori', 'lassi'] },
  },
  {
    slug: 'pink-city-handloom-bazaar-jaipur',
    title: 'Pink City Handloom Bazaar',
    categoryKey: 'shops',
    subtypeKey: 'handloom_bazaar',
    citySlug: 'jaipur',
    areaSlug: 'old-city-loop',
    vendorType: 'market',
    discoveryType: 'iconic_collection',
    vendor: { businessName: 'Pink City Handloom Bazaar', slug: 'pink-city-handloom-bazaar', description: 'Handloom and textile market with block prints, sarees, and curated Jaipur craft.', shortDescription: 'Textiles and block prints in the old city.', ownerName: 'Meera Sharma', ownerEmail: 'meera.sharma@togetherinindia.example', ownerPassword: 'Vendor@12345', citySlug: 'jaipur', state: 'Rajasthan', tags: ['handloom', 'sarees', 'textiles'], languages: ['Hindi', 'English'], yearEstablished: 2008 },
    location: { street: 'Tripolia Gate Road', area: 'Old City Loop', city: 'Jaipur', state: 'Rajasthan', pincode: '302002', coordinates: [75.8221, 26.9231] },
    tags: ['handloom', 'textiles', 'shopping', 'craft'],
    nearbyLandmarks: ['tripolia bazaar', 'city palace', 'johari bazaar'],
    areaCluster: 'pink-city-core',
    labels: { popularChoice: false, superSaver: false, sponsored: true, featured: true, openNow: true },
    pricing: { priceType: 'free', currency: 'INR', basePrice: 0, showPriceAs: 'hidden' },
    seoConfig: { metaTitle: 'Pink City Handloom Bazaar Jaipur', metaDescription: 'Seeded market discovery for Jaipur handloom shopping.', keywords: ['handloom', 'bazaar', 'jaipur market'] },
  },
  {
    slug: 'hawa-mahal-heritage-walk-jaipur',
    title: 'Hawa Mahal Heritage Walk',
    categoryKey: 'thingsToDo',
    subtypeKey: 'heritage_walk',
    citySlug: 'jaipur',
    areaSlug: 'old-city-loop',
    vendorType: 'other',
    discoveryType: 'featured',
    vendor: { businessName: 'Hawa Mahal Heritage Walks', slug: 'hawa-mahal-heritage-walks', description: 'Guided heritage walks through Jaipur palaces, lanes, and sunrise viewpoints.', shortDescription: 'Guided old city heritage walk.', ownerName: 'Rohan Singh', ownerEmail: 'rohan.singh@togetherinindia.example', ownerPassword: 'Vendor@12345', citySlug: 'jaipur', state: 'Rajasthan', tags: ['heritage', 'walking tour', 'sunrise'], languages: ['Hindi', 'English'], yearEstablished: 2015 },
    location: { street: 'Hawa Mahal Road', area: 'Old City Loop', city: 'Jaipur', state: 'Rajasthan', pincode: '302002', coordinates: [75.8233, 26.9248] },
    tags: ['heritage', 'walk', 'city tour', 'sunrise'],
    nearbyLandmarks: ['hawa mahal', 'city palace'],
    areaCluster: 'pink-city-core',
    labels: { popularChoice: true, superSaver: false, sponsored: false, featured: true, openNow: false },
    pricing: { priceType: 'per_person', currency: 'INR', basePrice: 499, discountedPrice: 399, showPriceAs: 'base' },
    seoConfig: { metaTitle: 'Hawa Mahal Heritage Walk Jaipur', metaDescription: 'Seeded guided walk through Jaipur old city.', keywords: ['heritage walk', 'jaipur tour'] },
  },
  {
    slug: 'lake-view-royal-kitchen-udaipur',
    title: 'Lake View Royal Kitchen',
    categoryKey: 'restaurants',
    subtypeKey: 'heritage_dining',
    citySlug: 'udaipur',
    areaSlug: 'lake-pichola',
    vendorType: 'restaurant',
    discoveryType: 'featured',
    vendor: { businessName: 'Lake View Royal Kitchen', slug: 'lake-view-royal-kitchen', description: 'Lake-facing dining room with Rajasthani thalis and evening courtyard seating.', shortDescription: 'Heritage dining beside Lake Pichola.', ownerName: 'Neha Rawat', ownerEmail: 'neha.rawat@togetherinindia.example', ownerPassword: 'Vendor@12345', citySlug: 'udaipur', state: 'Rajasthan', tags: ['heritage dining', 'lake view', 'thali'], languages: ['Hindi', 'English'], yearEstablished: 2010 },
    location: { street: 'Lake Pichola Road', area: 'Lake Pichola', city: 'Udaipur', state: 'Rajasthan', pincode: '313001', coordinates: [73.6827, 24.5788] },
    tags: ['thali', 'lake view', 'rajasthani', 'romantic dinner'],
    nearbyLandmarks: ['city palace', 'jagdish temple'],
    areaCluster: 'lake-city-core',
    labels: { popularChoice: true, superSaver: false, sponsored: false, featured: true, openNow: true },
    pricing: { priceType: 'range', currency: 'INR', basePrice: 900, minPrice: 650, maxPrice: 1800, showPriceAs: 'range' },
    seoConfig: { metaTitle: 'Lake View Royal Kitchen Udaipur', metaDescription: 'Heritage dining discovery on Lake Pichola.', keywords: ['udaipur food', 'lake pichola', 'heritage dining'] },
  },
  {
    slug: 'shilpgram-craft-avenue-udaipur',
    title: 'Shilpgram Craft Avenue',
    categoryKey: 'shops',
    subtypeKey: 'artisan_studio',
    citySlug: 'udaipur',
    areaSlug: 'sadar-bazaar-udaipur',
    vendorType: 'artisan_store',
    discoveryType: 'popular_choice',
    vendor: { businessName: 'Shilpgram Craft Avenue', slug: 'shilpgram-craft-avenue', description: 'Curated artisan store with miniature paintings, textiles, and handcrafted decor.', shortDescription: 'Artisan-led craft store in Udaipur.', ownerName: 'Aarav Joshi', ownerEmail: 'aarav.joshi@togetherinindia.example', ownerPassword: 'Vendor@12345', citySlug: 'udaipur', state: 'Rajasthan', tags: ['craft', 'artisan', 'decor'], languages: ['Hindi', 'English'], yearEstablished: 2014 },
    location: { street: 'Shilpgram Road', area: 'Sadar Bazaar', city: 'Udaipur', state: 'Rajasthan', pincode: '313001', coordinates: [73.7007, 24.5827] },
    tags: ['artisan', 'crafts', 'souvenir', 'handmade'],
    nearbyLandmarks: ['clock tower', 'city palace'],
    areaCluster: 'lake-city-market',
    labels: { popularChoice: true, superSaver: false, sponsored: true, featured: true, openNow: true },
    pricing: { priceType: 'contact_for_price', currency: 'INR', showPriceAs: 'hidden' },
    seoConfig: { metaTitle: 'Shilpgram Craft Avenue Udaipur', metaDescription: 'Artisan craft store seeded for discovery and nearby browsing.', keywords: ['artisans', 'craft store', 'udaipur shopping'] },
  },
  {
    slug: 'lake-palace-boutique-stay-udaipur',
    title: 'Lake Palace Boutique Stay',
    categoryKey: 'hotels',
    subtypeKey: 'lake_view_stay',
    citySlug: 'udaipur',
    areaSlug: 'lake-pichola',
    vendorType: 'boutique',
    discoveryType: 'sponsored',
    vendor: { businessName: 'Lake Palace Boutique Stay', slug: 'lake-palace-boutique-stay', description: 'Compact boutique stay designed for lake-side discovery trips and evening walks.', shortDescription: 'Boutique stay near Lake Pichola.', ownerName: 'Pooja Mehta', ownerEmail: 'pooja.mehta@togetherinindia.example', ownerPassword: 'Vendor@12345', citySlug: 'udaipur', state: 'Rajasthan', tags: ['boutique stay', 'lake view', 'heritage'], languages: ['Hindi', 'English'], yearEstablished: 2018 },
    location: { street: 'Pichola Gate Road', area: 'Lake Pichola', city: 'Udaipur', state: 'Rajasthan', pincode: '313001', coordinates: [73.6852, 24.5783] },
    tags: ['boutique stay', 'lake view', 'heritage', 'premium'],
    nearbyLandmarks: ['city palace', 'gangaur ghat'],
    areaCluster: 'lake-city-core',
    labels: { popularChoice: false, superSaver: false, sponsored: true, featured: true, openNow: true },
    pricing: { priceType: 'per_night', currency: 'INR', basePrice: 4200, minPrice: 3800, maxPrice: 7200, showPriceAs: 'base' },
    seoConfig: { metaTitle: 'Lake Palace Boutique Stay Udaipur', metaDescription: 'Seeded boutique stay for Lake Pichola discovery.', keywords: ['udaipur stay', 'lake pichola hotel'] },
  },
  {
    slug: 'chandni-chowk-spice-trail-delhi',
    title: 'Chandni Chowk Spice Trail',
    categoryKey: 'restaurants',
    subtypeKey: 'street_food',
    citySlug: 'delhi',
    areaSlug: 'chandni-chowk',
    vendorType: 'street_food',
    discoveryType: 'iconic_collection',
    vendor: { businessName: 'Chandni Chowk Spice Trail', slug: 'chandni-chowk-spice-trail', description: 'Classic Old Delhi snack house for parathas, chaats, and seasonal sweets.', shortDescription: 'Iconic Old Delhi street food stop.', ownerName: 'Sanjay Kapoor', ownerEmail: 'sanjay.kapoor@togetherinindia.example', ownerPassword: 'Vendor@12345', citySlug: 'delhi', state: 'Delhi', tags: ['street food', 'chaat', 'paratha'], languages: ['Hindi', 'English'], yearEstablished: 2004 },
    location: { street: 'Paranthe Wali Gali', area: 'Chandni Chowk', city: 'Delhi', state: 'Delhi', pincode: '110006', coordinates: [77.2317, 28.6565] },
    tags: ['street food', 'old delhi', 'chaat', 'paratha'],
    nearbyLandmarks: ['red fort', 'jama masjid'],
    areaCluster: 'old-delhi-core',
    labels: { popularChoice: true, superSaver: true, sponsored: false, featured: true, openNow: true },
    pricing: { priceType: 'range', currency: 'INR', basePrice: 150, minPrice: 60, maxPrice: 450, showPriceAs: 'range' },
    seoConfig: { metaTitle: 'Chandni Chowk Spice Trail Delhi', metaDescription: 'Old Delhi street food discovery seeded for public browsing.', keywords: ['delhi food', 'old delhi', 'chaat'] },
  },
  {
    slug: 'connaught-circle-coffee-house-delhi',
    title: 'Connaught Circle Coffee House',
    categoryKey: 'restaurants',
    subtypeKey: 'cafe',
    citySlug: 'delhi',
    areaSlug: 'connaught-place',
    vendorType: 'cafe',
    discoveryType: 'nearby',
    vendor: { businessName: 'Connaught Circle Coffee House', slug: 'connaught-circle-coffee-house', description: 'Central Delhi cafe for quick brunches, cold coffee, and business meetups.', shortDescription: 'Classic cafe in Connaught Place.', ownerName: 'Ananya Gupta', ownerEmail: 'ananya.gupta@togetherinindia.example', ownerPassword: 'Vendor@12345', citySlug: 'delhi', state: 'Delhi', tags: ['cafe', 'coffee', 'brunch'], languages: ['Hindi', 'English'], yearEstablished: 2016 },
    location: { street: 'Outer Circle', area: 'Connaught Place', city: 'Delhi', state: 'Delhi', pincode: '110001', coordinates: [77.2197, 28.631] },
    tags: ['coffee', 'brunch', 'cafe', 'central delhi'],
    nearbyLandmarks: ['rajiv chowk', 'janpath'],
    areaCluster: 'ncr-central',
    labels: { popularChoice: true, superSaver: false, sponsored: false, featured: true, openNow: true },
    pricing: { priceType: 'range', currency: 'INR', basePrice: 250, minPrice: 180, maxPrice: 900, showPriceAs: 'range' },
    seoConfig: { metaTitle: 'Connaught Circle Coffee House Delhi', metaDescription: 'Central Delhi cafe discovery for seed data browsing.', keywords: ['connaught place cafe', 'delhi coffee'] },
  },
  {
    slug: 'godowlia-silk-market-varanasi',
    title: 'Godowlia Silk Market',
    categoryKey: 'shops',
    subtypeKey: 'market_stall',
    citySlug: 'varanasi',
    areaSlug: 'godowlia',
    vendorType: 'market',
    discoveryType: 'iconic_collection',
    vendor: { businessName: 'Godowlia Silk Market', slug: 'godowlia-silk-market', description: 'Silk and brocade market with heritage textiles and festive gifting options.', shortDescription: 'Silk market near the ghats.', ownerName: 'Farhan Ansari', ownerEmail: 'farhan.ansari@togetherinindia.example', ownerPassword: 'Vendor@12345', citySlug: 'varanasi', state: 'Uttar Pradesh', tags: ['silk', 'brocade', 'market'], languages: ['Hindi', 'English'], yearEstablished: 2001 },
    location: { street: 'Godowlia Crossing', area: 'Godowlia', city: 'Varanasi', state: 'Uttar Pradesh', pincode: '221001', coordinates: [83.0055, 25.3081] },
    tags: ['silk', 'market', 'brocade', 'gifting'],
    nearbyLandmarks: ['vishwanath gali', 'dashashwamedh ghat'],
    areaCluster: 'ghat-market',
    labels: { popularChoice: true, superSaver: false, sponsored: true, featured: true, openNow: true },
    pricing: { priceType: 'contact_for_price', currency: 'INR', showPriceAs: 'hidden' },
    seoConfig: { metaTitle: 'Godowlia Silk Market Varanasi', metaDescription: 'Silk shopping market seeded for public discovery.', keywords: ['varanasi silk', 'godowlia market'] },
  },
  {
    slug: 'ganga-aarti-riverside-walk-varanasi',
    title: 'Ganga Aarti Riverside Walk',
    categoryKey: 'thingsToDo',
    subtypeKey: 'heritage_walk',
    citySlug: 'varanasi',
    areaSlug: 'dashashwamedh-ghat',
    vendorType: 'other',
    discoveryType: 'featured',
    vendor: { businessName: 'Ganga Aarti Riverside Walks', slug: 'ganga-aarti-riverside-walks', description: 'Evening walking route that ties the ghats, lamps, and temple lanes together.', shortDescription: 'Evening heritage walk in Varanasi.', ownerName: 'Priyanka Verma', ownerEmail: 'priyanka.verma@togetherinindia.example', ownerPassword: 'Vendor@12345', citySlug: 'varanasi', state: 'Uttar Pradesh', tags: ['aarti', 'walk', 'ghat'], languages: ['Hindi', 'English'], yearEstablished: 2017 },
    location: { street: 'Dashashwamedh Ghat', area: 'Dashashwamedh Ghat', city: 'Varanasi', state: 'Uttar Pradesh', pincode: '221001', coordinates: [83.0067, 25.3076] },
    tags: ['aarti', 'ghat', 'walking tour', 'spiritual'],
    nearbyLandmarks: ['ganga aarti', 'kashi vishwanath temple'],
    areaCluster: 'ghat-corridor',
    labels: { popularChoice: true, superSaver: false, sponsored: false, featured: true, openNow: false },
    pricing: { priceType: 'per_person', currency: 'INR', basePrice: 299, showPriceAs: 'base' },
    seoConfig: { metaTitle: 'Ganga Aarti Riverside Walk Varanasi', metaDescription: 'Seeded walking experience for Varanasi discovery.', keywords: ['varanasi walk', 'ganga aarti', 'ghat tour'] },
  },
  {
    slug: 'baga-sunset-shack-goa',
    title: 'Baga Sunset Shack',
    categoryKey: 'restaurants',
    subtypeKey: 'rooftop_dining',
    citySlug: 'goa',
    areaSlug: 'baga-beach',
    vendorType: 'bar_pub',
    discoveryType: 'nearby',
    vendor: { businessName: 'Baga Sunset Shack', slug: 'baga-sunset-shack', description: 'Beachside shack for seafood, cool drinks, and sunset service.', shortDescription: 'Beach shack near Baga.', ownerName: 'Ishaan Dsouza', ownerEmail: 'ishaan.dsouza@togetherinindia.example', ownerPassword: 'Vendor@12345', citySlug: 'goa', state: 'Goa', tags: ['beach shack', 'seafood', 'sunset'], languages: ['English', 'Hindi', 'Konkani'], yearEstablished: 2011 },
    location: { street: 'Titos Lane', area: 'Baga Beach', city: 'Goa', state: 'Goa', pincode: '403519', coordinates: [73.7512, 15.5561] },
    tags: ['beach shack', 'seafood', 'sunset', 'goa nightlife'],
    nearbyLandmarks: ['baga beach', 'calangute beach'],
    areaCluster: 'north-goa-beach',
    labels: { popularChoice: true, superSaver: false, sponsored: false, featured: true, openNow: true },
    pricing: { priceType: 'range', currency: 'INR', basePrice: 350, minPrice: 200, maxPrice: 1600, showPriceAs: 'range' },
    seoConfig: { metaTitle: 'Baga Sunset Shack Goa', metaDescription: 'Beach shack discovery for Goa sunset browsing.', keywords: ['goa shack', 'baga beach', 'seafood'] },
  },
  {
    slug: 'fontainhas-colonial-stay-goa',
    title: 'Fontainhas Colonial Stay',
    categoryKey: 'hotels',
    subtypeKey: 'boutique_stay',
    citySlug: 'goa',
    areaSlug: 'panaji-fountainhas',
    vendorType: 'boutique',
    discoveryType: 'featured',
    vendor: { businessName: 'Fontainhas Colonial Stay', slug: 'fontainhas-colonial-stay', description: 'Boutique stay in the Latin quarter with heritage architecture and quiet lanes.', shortDescription: 'Boutique stay in Panaji old quarter.', ownerName: 'Valentina Pereira', ownerEmail: 'valentina.pereira@togetherinindia.example', ownerPassword: 'Vendor@12345', citySlug: 'goa', state: 'Goa', tags: ['heritage stay', 'boutique', 'latin quarter'], languages: ['English', 'Hindi', 'Konkani'], yearEstablished: 2019 },
    location: { street: 'Fontainhas Lane', area: 'Fontainhas', city: 'Goa', state: 'Goa', pincode: '403001', coordinates: [73.8317, 15.4989] },
    tags: ['boutique stay', 'heritage', 'latin quarter'],
    nearbyLandmarks: ['panjim church', 'mandovi river'],
    areaCluster: 'panaji-core',
    labels: { popularChoice: false, superSaver: false, sponsored: true, featured: true, openNow: true },
    pricing: { priceType: 'per_night', currency: 'INR', basePrice: 5800, minPrice: 4500, maxPrice: 9200, showPriceAs: 'base' },
    seoConfig: { metaTitle: 'Fontainhas Colonial Stay Goa', metaDescription: 'Heritage stay seeded for Goa discovery pages.', keywords: ['goa stay', 'fontainhas', 'boutique stay'] },
  },
];

export { categoriesData, subtypesData, citiesData, seededAreas, seededDiscoveryListings };