import authRoutes from '../modules/auth/auth.routes.js';
import usersRoutes from '../modules/users/users.routes.js';
import vendorsRoutes from '../modules/vendors/vendors.routes.js';
import categoriesRoutes from '../modules/categories/categories.routes.js';
import subtypesRoutes from '../modules/subtypes/subtypes.routes.js';
import templatesRoutes from '../modules/templates/templates.routes.js';
import citiesRoutes from '../modules/cities/cities.routes.js';
import areasRoutes from '../modules/areas/areas.routes.js';
import listingsRoutes from '../modules/listings/listings.routes.js';
import hotelsRoutes from '../modules/hotels/hotels.routes.js';
import thingsToDoRoutes from '../modules/thingsToDo/thingsToDo.routes.js';
import restaurantsRoutes from '../modules/restaurants/restaurants.routes.js';
import shopsRoutes from '../modules/shops/shops.routes.js';
import tribesRoutes from '../modules/tribes/tribes.routes.js';
import kidsWorldRoutes from '../modules/kidsWorld/kidsWorld.routes.js';
import destinationsRoutes from '../modules/destinations/destinations.routes.js';
import cmsRoutes from '../modules/cms/cms.routes.js';
import pagesRoutes from '../modules/pages/pages.routes.js';
import plansRoutes from '../modules/plans/plans.routes.js';
import subscriptionsRoutes from '../modules/subscriptions/subscriptions.routes.js';
import slotsRoutes from '../modules/slots/slots.routes.js';
import monetizationRoutes from '../modules/monetization/monetization.routes.js';
import luckyDrawRoutes from '../modules/luckyDraw/luckyDraw.routes.js';
import analyticsRoutes from '../modules/analytics/analytics.routes.js';
import reportsRoutes from '../modules/reports/reports.routes.js';
import uploadsRoutes from '../modules/uploads/uploads.routes.js';
import searchRoutes from '../modules/search/search.routes.js';
import discoveryRoutes from '../modules/discovery/discovery.routes.js';
import collectionsRoutes from '../modules/collections/collections.routes.js';
import editorialRoutes from '../modules/editorial/editorial.routes.js';
import notificationsRoutes from '../modules/notifications/notifications.routes.js';
import wishlistRoutes from '../modules/wishlist/wishlist.routes.js';
import inquiriesRoutes from '../modules/inquiries/inquiries.routes.js';
import seoRoutes from '../modules/seo/seo.routes.js';
import securityRoutes from '../modules/security/security.routes.js';
import systemRoutes from '../modules/system/system.routes.js';
import bookingHubRoutes from '../modules/bookingHub/bookingHub.routes.js';
import env from '../config/env.js';

const registerRoutes = (app) => {
  const base = `/api/${env.API_VERSION}`;

  app.use(`${base}/auth`, authRoutes);
  app.use(`${base}/users`, usersRoutes);
  app.use(`${base}/vendors`, vendorsRoutes);
  app.use(`${base}/categories`, categoriesRoutes);
  app.use(`${base}/subtypes`, subtypesRoutes);
  app.use(`${base}/templates`, templatesRoutes);
  app.use(`${base}/cities`, citiesRoutes);
  app.use(`${base}/areas`, areasRoutes);
  app.use(`${base}/listings`, listingsRoutes);
  app.use(`${base}/hotels`, hotelsRoutes);
  app.use(`${base}/things-to-do`, thingsToDoRoutes);
  app.use(`${base}/restaurants`, restaurantsRoutes);
  app.use(`${base}/shops`, shopsRoutes);
  app.use(`${base}/tribes`, tribesRoutes);
  app.use(`${base}/kids-world`, kidsWorldRoutes);
  app.use(`${base}/destinations`, destinationsRoutes);
  app.use(`${base}/cms`, cmsRoutes);
  app.use(`${base}/pages`, pagesRoutes);
  app.use(`${base}/plans`, plansRoutes);
  app.use(`${base}/subscriptions`, subscriptionsRoutes);
  app.use(`${base}/slots`, slotsRoutes);
  app.use(`${base}/monetization`, monetizationRoutes);
  app.use(`${base}/lucky-draw`, luckyDrawRoutes);
  app.use(`${base}/analytics`, analyticsRoutes);
  app.use(`${base}/reports`, reportsRoutes);
  app.use(`${base}/uploads`, uploadsRoutes);
  app.use(`${base}/search`, searchRoutes);
  app.use(`${base}/discovery`, discoveryRoutes);
  app.use(`${base}/collections`, collectionsRoutes);
  app.use(`${base}/editorial`, editorialRoutes);
  app.use(`${base}/notifications`, notificationsRoutes);
  app.use(`${base}/wishlist`, wishlistRoutes);
  app.use(`${base}/inquiries`, inquiriesRoutes);
  app.use(`${base}/seo`, seoRoutes);
  app.use(`${base}/security`, securityRoutes);
  app.use(`${base}/system`, systemRoutes);
  app.use(`${base}`, bookingHubRoutes);
};

export default registerRoutes;
